### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Jameriquiah** [GarciaLnk/OoT3DCameraControl#1]
i activated the exe after loading into the game and it said found localplayer and found localcamera and had the offsets and everything and it even said controller 0 is connected but it doesnt work the right stick still does nothing

**Comment by AnathemaSoul** [comment]
On my end, I open the game and get control of link, boot the .exe, and it just sits at "Successfully hooked to citra-qt.exe, finding memory addresses..." forever and never activates.

**Comment by GarciaLnk** [comment]
Can't reproduce
