### ISSUE TITLE
Sorry but it is not working!

### ISSUE THREAD

**Issue by ggperes2019** [GarciaLnk/OoT3DCameraControl#6]
I tried all different versions and running Citra Nightly(also tried Citra Canary) but it doesnt work!
The .exe open a screen that says "Successfully hooked to citra.exe, finding memory addresses..."
nothing happens, camera on c-stick doesn't work(maybe the application is not finding the memory address) and the aplication close itself alone after some time.

Do i need to install or configure something else in Windows? My rom is usa region btw.

Thanks for reading!

**Comment by GarciaLnk** [comment]
You can try this mod if the hack doesn't work for you: https://github.com/Roberto-Nessy/OoT3D_Standalone_Free_Cam
